sonar.projectKey=oscharko-dev_Keiko-Native
sonar.organization=oscharko-dev
sonar.projectName=Keiko Native
sonar.sourceEncoding=UTF-8
sonar.sources=quality
sonar.tests=quality
sonar.test.inclusions=quality/*.test.mjs
sonar.exclusions=quality/*.test.mjs,coverage/**,node_modules/**
sonar.coverage.exclusions=quality/check.mjs,quality/markdown.mjs,quality/smoke.mjs
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.scm.provider=git
sonar.plsql.file.suffixes=-
